#!/bin/bash

for x in base/comment \
         base/declarations \
         base/base1 \
    base/checkstacksize \
    base/done \
    base/error \
    base/lex \
    base/lookup \
    base/pop \
    base/poptoken \
    base/push \
    base/pushtoken \
    base/recovering \
    base/reduce \
    base/reset \
    base/setdebug \
    base/shift
do
    echo "// $x" >> bisonc++.cc
    cat $x >> bisonc++.cc
done


for x in \
    derived/errorrecovery \
    derived/executeaction \
    derived/gettoken \
    derived/needtoken \
    derived/nextcycle \
    derived/parse \
    derived/print
do
    echo "// $x" >> bisonc++.cc
    cat $x >> bisonc++.cc
done


for x in hdr/includes \
         hdr/baseclass \
    hdr/abort \
    hdr/accept \
    hdr/debug \
    hdr/error \
    hdr/top \
    hdr/opbitand \
    hdr/opbitor \
    hdr/stacksize \
    hdr/terminaltoken \
    hdr/token \
    hdr/nexttoken \
    hdr/vs \
    hdr/tail
do
    echo "// $x" >> bisonc++base.h
    cat $x >> bisonc++base.h
done

mv bisonc++* ../skeletons/




