#!/bin/sh

SKEL=../../../../share/bisonc++

BISON=bisonc++
BISON="../../../../tmp/bin/bisonc++ -B ${SKEL}base.h -C ${SKEL}.h -I ${SKEL}.ih -P ${SKEL}.cc"

case $1 in
    (clean)
        rm -rf scanner/yylex.cc demo parser/{parse.*,parserbase.h}
    ;;
    (demo)
        cd parser
        $BISON -V --show-filenames  grammar
        cd ..
        cd scanner
        flex lexer
        cd ..
        g++ -Wall -o demo *.cc */*.cc
    ;;
    (*)
        echo "$0 [clean|demo] to clean or build the demo program"
    ;;
esac
