#!/bin/sh
PROJECT=bisoncpp

cvsremove

mkdir -p tmp

cd bisonc++

mkdir -p flex
cp /usr/include/FlexLexer.h flex

make/clean

cd scanner 
[ -e yylex.cc ] || req flex lexer
cd ..

make/program
make/man
make/manual

mv tmp/bin ../tmp
mv tmp/o   ../tmp
mv libbisonc++.a ../tmp

export BISONCPP=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..
rm -rf tmp

cvsrestore



