#!/bin/sh
PROJECT=bisoncpp

cvsremove

if [ ! -e usage ] 
then
    echo g++ -o usage usage.cc bisonc++/usage.cc
    g++ -o usage usage.cc bisonc++/usage.cc
fi

cd bisonc++

# If a new package must be created for lintian/linda, then comment all below 
# until the `export' line

mkdir -p flex
cp /usr/include/FlexLexer.h flex

make/distclean

../usage > documentation/manual/invoking/usage

cd scanner 
[ -e yylex.cc ] || req flex lexer
cd ..

make/man
make/manual

export BISONCPP=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

echo LINTIAN ...
lintian -i *.changes
echo LINDA ...
linda -i *.changes

