#!/bin/sh
PROJECT=bisoncpp

cvsremove

cd bisonc++

export BISONCPP=minimal 

make/clean
make/program
make/man
make/manual

export BISONCPP=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

