#!/bin/bash
PROJECT=bisonc++

                                        # load the version
VERSION=`grep VERSION ${PROJECT}/VERSION |
    sed 's/#define[[:space:]]\+VERSION[[:space:]]\+"\(.*\)"/\1/'`

DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

tgz()
{
    ln -s ${PROJECT} ${DISTRIBUTION}        # distribution's dir name

    tar czvf $1 --exclude-from=excluded  ${DISTRIBUTION}/*

    rm ${DISTRIBUTION}                      # rm the link
}

case "$1" in 
    (o)
        tgz ${HOME}/debian/${PROJECT}/tarballs/${PROJECT}_${VERSION}.orig.tar.gz
    ;;

    (t|u)
        tgz ${PROJECT}_${VERSION}.tar.gz

        if [ "$1" == "u" ]
        then
            scp ${PROJECT}_${VERSION}.tar.gz \
                                        oosix:ftp/debian/${PROJECT}
            md5sum ${PROJECT}_${VERSION}.tar.gz
        fi
    ;;

    (*)
        echo "
Provide arg:
    o (orig.tar.gz) to create a local .orig.tar.gz archive in 
                    ../debian/${PROJECT}/tarballs
    t (tar.gz)      to create ${PROJECT}_${VERSION}.tar.gz in this directory
    u (upload)      same as 't', but upload to oosix and show MD5 hash
"
    exit 1
    ;;

esac

