#!/bin/bash
PROJECT=bisonc++

                                        # load the version
VERSION=`grep VERSION ${PROJECT}/VERSION |
    sed 's/#define[[:space:]]\+VERSION[[:space:]]\+"\(.*\)"/\1/'`

DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

ln -s ${PROJECT} ${DISTRIBUTION}        # distribution's dir name

if [ "$#" != "0" ]                      # any arg? make debian .orig file
then
                                        # create the .orig source tar
    tar czvf \
        ${HOME}/debian/bisonc++/tarballs/${PROJECT}_${VERSION}.orig.tar.gz \
             --exclude-from=excluded  ${DISTRIBUTION}/*
else
    tar czvf ${PROJECT}_${VERSION}.tar.gz \
             --exclude-from=excluded  ${DISTRIBUTION}/*
fi

rm ${DISTRIBUTION}                      # rm the link

