#!/bin/bash

echo if any modified or untracked files are shown, handle these first:
echo
git st
echo -n "Continue [y/n] ? "
read yesno
[ "$yesno" == "y" ] || exit 0

echo -n "Need to (re)create bisoncpp's wip files for gh-pages [y/N] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    git co master
    cd bisonc++
    ./build man
    ./build manual
    ./build github
    ./build distclean
    cd ..    
    git co gh-pages

    rm --rf manual
    mv ../wip/changelog.txt ../wip/bisonc++man.html ../wip/manual .
    rm -r manual/essence
fi

echo
echo -n "Check index.yo: version and last 5 releases [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    emacs index.yo
fi

yodl2html index.yo || exit 1

echo "Running 'git st': check for unexpected files"
git st

echo

echo -n "ci change to index.html etc., push the result and co master [y/N] ? "
read yesno

if [ "$yesno" == "y" ] ; then

    echo -n "Enter the ci message: "
    read msg;

    RELEASE=`head -n1 ../wip/release.yo | 
                sed 's/SUBST(_CurVers_)(\(.*\))/\1/'`
    git ci -am "$msg"
    git push
    git co master
fi



