#!/bin/sh

. INSTALL.cf

echo "#define _Skel_  \"$SKEL\"" > parser/SKEL

run()
{
    echo "$*"
    $* || exit 1
}

run mkdir -p o $BIN $SKEL $MAN $DOC/{man,bison-docs}

run cd scanner 
[ -e yylex.cc ] || run flex lexer
run cd ..

for src in *.cc
do
    BASE=${src%\.[^\.]*}
    [ o/${BASE}.o -nt ${src} ] || run g++ -Wall -O3 -o o/${BASE}.o -c ${src}
done

NR=0
for x in element firstset symbol terminal block production followset \
         nonterminal symtab rules lookaheadset scanner parser \
         item state itemsets generator 
do
    run cd $x
    run mkdir -p o
    for src in *.cc
    do
        BASE=${src%\.[^\.]*}
        [ o/${NR}${BASE}.o -nt ${src} ] ||
            run g++ -Wall -O3 -o  o/${NR}${BASE}.o -c ${src}
    done
    run cd ..
    let NR=${NR}+1
done

[ -e libbisonc++.a ] || run ar rs libbisonc++.a o/*.o */o/*o
run g++ -o ${BIN}/bisonc++ -lbisonc++ -L. -lbobcat -s

run cp -r share/*   ${SKEL}
run cp -r documentation/bisonc++/usr/share/man/man1/*       ${MAN}
run cp -r COPYING documentation/examples                    ${DOC}
run cp -r documentation/man/calculator                      ${DOC}/man
run cp -r documentation/{html,bison.ps.org}                 ${DOC}/bison-docs
run cp -r documentation/bisonc++/usr/share/doc/bisonc++/manual  ${DOC}
