#!/bin/sh

case $1 in
    (clean)
        rm -rf scanner/yylex.cc demo Parser*.h parse.*
    ;;
    (demo)
        bisonc++ -V -l expressions
        cd scanner
        flex lexer
        cd ..
        g++ -Wall -o demo *.cc */*.cc
    ;;
    (*)
        echo "$0 [clean|demo] to clean or build the demo program"
    ;;
esac
