#!/bin/bash

case $1 in
    (clean)
	rm -f rpn
	cd parser
	rm -f Parser.h Parserbase.h parse.cc grammar.output
    ;;
    (rpn)
        cd parser
        bisonc++ -V grammar || exit 1

        cd ..
        g++ --std=c++14 -Wall -o rpn *.cc */*.cc
    ;;
    (*)
        echo "$0 [clean|rpn] to clean or build the rpn program"
    ;;
esac
