#!/bin/bash

WD=`pwd`

cd ../bisonc++ 
    build manual || exit 1
    build man || exit 1
cd $WD

yodl2html index.yo || exit 1

scp ../bisonc++/tmp/man*/*.html index.html \
    fbb,bisoncpp@web.sourceforge.net:htdocs/

cd ../bisonc++ 
    build distclean
