#!/bin/sh

DEBUG=--debug
#CONSTRUCTION=--construction

SKEL=../../../share/bisonc++

BISON=bisonc++
BISON="../../../tmp/bin/bisonc++ -B ${SKEL}base.h -C ${SKEL}.h -I ${SKEL}.ih -P ${SKEL}.cc"


case $1 in
    (clean)
        rm -rf scanner/yylex.cc demo Parser*.h parse.*
    ;;
    (demo)
        $BISON -V $DEBUG $CONSTRUCTION -l expressions
        cd scanner
        flex lexer
        cd ..
        g++ -Wall -o demo *.cc */*.cc
    ;;
    (*)
        echo "$0 [clean|demo] to clean or build the demo program"
    ;;
esac
