#!/bin/bash

case $1 in
    (clean)
        rm -f calc
        cd parser
        rm -f Parser.h Parserbase.h parse.cc grammar.output
    ;;
    (calc)
        cd parser
        bisonc++ -V grammar

        cd ..
        g++ --std=c++14 -Wall -o calc *.cc */*.cc
    ;;
    (*)
        echo "$0 [clean|calc] to clean or build the calc program"
    ;;
esac
