#!/bin/sh

. INSTALL.cf

make/special

req()
{
    echo "$*"
    $* || exit 1
}

make/special

mkdir -p tmp/man tmp/manhtml

MANPAGE=../../tmp/man/bisonc++.1
MANHTML=../../tmp/manhtml/bisonc++man.html

req cd documentation/man

if [ ! -e $MANPAGE -o bisonc++.yo -nt $MANPAGE -o \
    ../../release.yo -nt $MANPAGE ] 
then
    req yodl2html -o $MANHTML bisonc++
    req yodl2man -o $MANPAGE bisonc++
fi

cd ../..

