#!/bin/sh

. INSTALL.cf
. make/parameters


req()
{
    echo "$*"
    $* || exit 1
}

if [ -e ../tmp/libbisonc++.a ] 
then
    mv ../tmp/libbisonc++.a .
    mv ../tmp/*             tmp
else
    mkdir -p tmp/bin tmp/o

    make/special skel
    make/scanner
    make/library
    
    BASE=${MAIN%\.[^\.]*}
    OBJ=tmp/o/${BASE}.o
    
    [ ! -e $OBJ -o $MAIN -nt $OBJ ] &&
                         req g++ $COPTS -o $OBJ -c $MAIN
    
    req g++ -o tmp/bin/$EXECUTABLE $OBJ $LOPTS
fi




