#!/bin/sh

. INSTALL.cf
. make/parameters

req()
{
    echo "$*"
    $* || exit 1
}

mkdir -p tmp/bin tmp/o

make/special skel
make/library

BASE=${MAIN%\.[^\.]*}
OBJ=tmp/o/${BASE}.o

[ ! -e $OBJ -o $MAIN -nt $OBJ ] && req $GCC $COPTS -o $OBJ -c $MAIN

req $GCC -o tmp/bin/$EXECUTABLE $OBJ $LOPTS




